# Generated by Django 2.2.2 on 2019-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('location_found', models.CharField(max_length=100)),
                ('date_found', models.DateField()),
            ],
        ),
    ]
