# Generated by Django 2.1.2 on 2019-06-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shown', models.DateField()),
                ('highest_offer', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('P', 'Sale Pending')], default='A', max_length=1)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Gem')),
            ],
        ),
    ]
