# Generated by Django 2.1.2 on 2019-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={'ordering': ['-date_shown']},
        ),
        migrations.AlterField(
            model_name='display',
            name='date_shown',
            field=models.DateField(verbose_name='date shown'),
        ),
        migrations.AlterField(
            model_name='gem',
            name='date_found',
            field=models.DateField(verbose_name='date found'),
        ),
    ]
