# Generated by Django 2.1.2 on 2019-06-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190622_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gem',
            name='emotions',
            field=models.ManyToManyField(to='main_app.Emotion'),
        ),
    ]
